version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_ENABLE_AI_FIX=true
      - NEXT_PUBLIC_ENABLE_EXPORT=true
      - NEXT_PUBLIC_ENABLE_PLAYGROUND=true
      - NEXT_PUBLIC_CACHE_MAX_AGE=3600
      - NEXT_PUBLIC_CACHE_MAX_SIZE=100
      - NEXT_PUBLIC_MAX_MERMAID_SIZE=100000
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3